/*
 * FILE: EC_IvtrEquipMatter.cpp
 *
 * DESCRIPTION: 
 *
 * CREATED BY: Hedi, 2006/8/3
 *
 * HISTORY: 
 *
 * Copyright (c) 2006 Archosaur Studio, All Rights Reserved.
 */


#include "EC_Global.h"
#include "EC_IvtrEquipMatter.h"
#include "EC_Game.h"
#include "EC_FixedMsg.h"
#include "EC_GameRun.h"
#include "EC_RTDebug.h"
#include "elementdataman.h"
#include "EC_Configs.h"

///////////////////////////////////////////////////////////////////////////
//	
//	Define and Macro
//	
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
//	
//	Reference to External variables and functions
//	
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
//	
//	Local Types and Variables and Global variables
//	
///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////
//	
//	Local functions
//	
///////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////
//	
//	Implement CECIvtrBible
//	
///////////////////////////////////////////////////////////////////////////

CECIvtrBible::CECIvtrBible(int tid, int expire_date) : CECIvtrEquip(tid, expire_date)
{
	m_iCID	= ICID_BIBLE;

	//	Get database data
	elementdataman* pDB = g_pGame->GetElementDataMan();
	DATA_TYPE DataType;
	m_pDBEssence = (BIBLE_ESSENCE*)pDB->get_data_ptr(tid, ID_SPACE_ESSENCE, DataType);

	m_iPileLimit	= m_pDBEssence->pile_num_max;
	m_iPrice		= m_pDBEssence->price;
	m_iShopPrice	= m_pDBEssence->shop_price;
	m_iProcType		= m_pDBEssence->proc_type;
	m_i64EquipMask	= EQUIP_MASK64_BIBLE;

	m_iCurEndurance = 100;
	m_iMaxEndurance = 100;

	m_bNeedUpdate	= false;
}

CECIvtrBible::CECIvtrBible(const CECIvtrBible& s) : CECIvtrEquip(s)
{
	m_pDBEssence	= s.m_pDBEssence;
}

CECIvtrBible::~CECIvtrBible()
{
}

//	Set item detail information
bool CECIvtrBible::SetItemInfo(BYTE* pInfoData, int iDataLen)
{
	CECIvtrItem::SetItemInfo(pInfoData, iDataLen);
	return true;
}

//	Get item icon file name
const char* CECIvtrBible::GetIconFile()
{
	return m_pDBEssence->file_icon;
}

//	Get item name
const wchar_t* CECIvtrBible::GetName()
{
	return m_pDBEssence->name;
}

//	Get item description text
const wchar_t* CECIvtrBible::GetNormalDesc(bool bRepair)
{
	return m_strDesc;
}

//	Get drop model for shown
const char * CECIvtrBible::GetDropModel()
{
	return m_pDBEssence->file_matter;
}

//	Add deadly strike rate provided by this equipment 
//	bSuite: true, get deadly strike generated by suite
//  By Sunxuewei 2008/9/3
int CECIvtrBible::GetDeadlyStrikeRate(bool bSuiteGen)
{
	if (bSuiteGen)
		return CECIvtrEquip::GetDeadlyStrikeRate(bSuiteGen);
	
	int iVal = 0;

	//	Get database data
	elementdataman* pDataMan = g_pGame->GetElementDataMan();
	CECGame::ItemExtPropTable& PropTab = g_pGame->GetItemExtPropTable();

	for(int i=0; i < 10; i++)
	{
		int idProp = (int)m_pDBEssence->id_addons[i];	

		CECGame::ItemExtPropTable::pair_type Pair = PropTab.get(idProp);
		BYTE byPropType = Pair.second ? *Pair.first : 0xff;

		if (byPropType == 45)	//	Deadly strike
		{
			DATA_TYPE DataType = DT_INVALID;
			const void* pData = pDataMan->get_data_ptr(idProp, ID_SPACE_ADDON, DataType);
			if (DataType != DT_EQUIPMENT_ADDON)
			{
				ASSERT(DataType == DT_EQUIPMENT_ADDON);
				return 0;
			}
			
			const EQUIPMENT_ADDON* pAddon = (const EQUIPMENT_ADDON*)pData;						
			float* fTemp = (float*)&pAddon->param1;			
			iVal += (int)(*fTemp*100 + 0.001f);
		}
	}

	return iVal;
}
///////////////////////////////////////////////////////////////////////////
//	
//	Implement CECIvtrSpeaker
//	
///////////////////////////////////////////////////////////////////////////

CECIvtrSpeaker::CECIvtrSpeaker(int tid, int expire_date) : CECIvtrEquip(tid, expire_date)
{
	m_iCID	= ICID_SPEAKER;

	//	Get database data
	elementdataman* pDB = g_pGame->GetElementDataMan();
	DATA_TYPE DataType;
	m_pDBEssence = (SPEAKER_ESSENCE*)pDB->get_data_ptr(tid, ID_SPACE_ESSENCE, DataType);

	m_iPileLimit	= m_pDBEssence->pile_num_max;
	m_iPrice		= m_pDBEssence->price;
	m_iShopPrice	= m_pDBEssence->shop_price;
	m_iProcType		= m_pDBEssence->proc_type;
	m_i64EquipMask	= EQUIP_MASK64_SPEAKER;

	m_iCurEndurance = 100;
	m_iMaxEndurance = 100;

	m_bNeedUpdate	= false;
}

CECIvtrSpeaker::CECIvtrSpeaker(const CECIvtrSpeaker& s) : CECIvtrEquip(s)
{
	m_pDBEssence	= s.m_pDBEssence;
}

CECIvtrSpeaker::~CECIvtrSpeaker()
{
}

//	Set item detail information
bool CECIvtrSpeaker::SetItemInfo(BYTE* pInfoData, int iDataLen)
{
	CECIvtrItem::SetItemInfo(pInfoData, iDataLen);
	return true;
}

//	Get item icon file name
const char* CECIvtrSpeaker::GetIconFile()
{
	return m_pDBEssence->file_icon;
}

//	Get item name
const wchar_t* CECIvtrSpeaker::GetName()
{
	return m_pDBEssence->name;
}

//	Get item description text
const wchar_t* CECIvtrSpeaker::GetNormalDesc(bool bRepair)
{
	
	return m_strDesc;
}

//	Get drop model for shown
const char * CECIvtrSpeaker::GetDropModel()
{
	return m_pDBEssence->file_matter;
}


///////////////////////////////////////////////////////////////////////////
//	
//	Implement CECIvtrAutoHP
//	
///////////////////////////////////////////////////////////////////////////

CECIvtrAutoHP::CECIvtrAutoHP(int tid, int expire_date) : CECIvtrEquip(tid, expire_date)
{
	m_iCID	= ICID_AUTOHP;

	//	Get database data
	elementdataman* pDB = g_pGame->GetElementDataMan();
	DATA_TYPE DataType;
	m_pDBEssence = (AUTOHP_ESSENCE*)pDB->get_data_ptr(tid, ID_SPACE_ESSENCE, DataType);

	m_iPileLimit	= m_pDBEssence->pile_num_max;
	m_iPrice		= m_pDBEssence->price;
	m_iShopPrice	= m_pDBEssence->shop_price;
	m_iProcType		= m_pDBEssence->proc_type;
	m_i64EquipMask	= EQUIP_MASK64_AUTOHP;

	m_iCurEndurance = 100;
	m_iMaxEndurance = 100;
}

CECIvtrAutoHP::CECIvtrAutoHP(const CECIvtrAutoHP& s) : CECIvtrEquip(s)
{
	m_pDBEssence	= s.m_pDBEssence;
	m_Essence		= s.m_Essence;
}

CECIvtrAutoHP::~CECIvtrAutoHP()
{
}

//	Set item detail information
bool CECIvtrAutoHP::SetItemInfo(BYTE* pInfoData, int iDataLen)
{
	CECIvtrItem::SetItemInfo(pInfoData, iDataLen);

	if (!pInfoData || !iDataLen)
		return true;
	
	try
	{
		CECDataReader dr(pInfoData, iDataLen);

		m_Essence = *(IVTR_ESSENCE_AUTOHP*)dr.Read_Data(sizeof (IVTR_ESSENCE_AUTOHP));
	}
	catch (CECException& e)
	{
		ASSERT(0);
		a_LogOutput(1, "CECIvtrAutoHP::SetItemInfo, data read error (%d)", e.GetType());
		return false;
	}

	return true;
}

//	Get item icon file name
const char* CECIvtrAutoHP::GetIconFile()
{
	return m_pDBEssence->file_icon;
}

//	Get item name
const wchar_t* CECIvtrAutoHP::GetName()
{
	return m_pDBEssence->name;
}

//	Get item description text
const wchar_t* CECIvtrAutoHP::GetNormalDesc(bool bRepair)
{
	
	return m_strDesc;
}

//	Get drop model for shown
const char * CECIvtrAutoHP::GetDropModel()
{
	return m_pDBEssence->file_matter;
}

//	Get item cool time
int CECIvtrAutoHP::GetCoolTime(int* piMax)
{
	return 0;
}


///////////////////////////////////////////////////////////////////////////
//	
//	Implement CECIvtrAutoMP
//	
///////////////////////////////////////////////////////////////////////////

CECIvtrAutoMP::CECIvtrAutoMP(int tid, int expire_date) : CECIvtrEquip(tid, expire_date)
{
	m_iCID	= ICID_AUTOMP;

	//	Get database data
	elementdataman* pDB = g_pGame->GetElementDataMan();
	DATA_TYPE DataType;
	m_pDBEssence = (AUTOMP_ESSENCE*)pDB->get_data_ptr(tid, ID_SPACE_ESSENCE, DataType);

	m_iPileLimit	= m_pDBEssence->pile_num_max;
	m_iPrice		= m_pDBEssence->price;
	m_iShopPrice	= m_pDBEssence->shop_price;
	m_iProcType		= m_pDBEssence->proc_type;
	m_i64EquipMask	= EQUIP_MASK64_AUTOMP;

	m_iCurEndurance = 100;
	m_iMaxEndurance = 100;
}

CECIvtrAutoMP::CECIvtrAutoMP(const CECIvtrAutoMP& s) : CECIvtrEquip(s)
{
	m_pDBEssence	= s.m_pDBEssence;
	m_Essence		= s.m_Essence;
}

CECIvtrAutoMP::~CECIvtrAutoMP()
{
}

//	Set item detail information
bool CECIvtrAutoMP::SetItemInfo(BYTE* pInfoData, int iDataLen)
{
	CECIvtrItem::SetItemInfo(pInfoData, iDataLen);

	if (!pInfoData || !iDataLen)
		return true;

	try
	{
		CECDataReader dr(pInfoData, iDataLen);

		m_Essence = *(IVTR_ESSENCE_AUTOMP*)dr.Read_Data(sizeof (IVTR_ESSENCE_AUTOMP));
	}
	catch (CECException& e)
	{
		ASSERT(0);
		a_LogOutput(1, "CECIvtrAutoHP::SetItemInfo, data read error (%d)", e.GetType());
		return false;
	}

	return true;
}

//	Get item icon file name
const char* CECIvtrAutoMP::GetIconFile()
{
	return m_pDBEssence->file_icon;
}

//	Get item name
const wchar_t* CECIvtrAutoMP::GetName()
{
	return m_pDBEssence->name;
}

//	Get item description text
const wchar_t* CECIvtrAutoMP::GetNormalDesc(bool bRepair)
{
	return m_strDesc;
}

//	Get drop model for shown
const char * CECIvtrAutoMP::GetDropModel()
{
	return m_pDBEssence->file_matter;
}

//	Get item cool time
int CECIvtrAutoMP::GetCoolTime(int* piMax)
{
	return 0;
}



///////////////////////////////////////////////////////////////////////////
//	
//	Implement CECIvtrCertificate
//	
///////////////////////////////////////////////////////////////////////////

CECIvtrCertificate::CECIvtrCertificate(int tid, int expire_date) : CECIvtrEquip(tid, expire_date)
{
	m_iCID	= ICID_CERTIFICATE;

	//	Get database data
	elementdataman* pDB = g_pGame->GetElementDataMan();
	DATA_TYPE DataType;
	m_pDBEssence	= (SELL_CERTIFICATE_ESSENCE*)pDB->get_data_ptr(tid, ID_SPACE_ESSENCE, DataType);

	m_iSellColNum	= m_pDBEssence->num_sell_item;
	m_iBuyColNum	= m_pDBEssence->num_buy_item;
	m_iBoothNameLength	= m_pDBEssence->max_name_length;
	m_iPrice	=	m_pDBEssence->price;
	m_i64EquipMask = EQUIP_MASK64_CERTIFICATE;

	m_iCurEndurance = 100;
	m_iMaxEndurance = 100;

	m_bNeedUpdate	= false;
}

CECIvtrCertificate::CECIvtrCertificate(const CECIvtrCertificate& s) : CECIvtrEquip(s)
{
	m_pDBEssence	= s.m_pDBEssence;

	m_iSellColNum	= s.m_pDBEssence->num_sell_item;
	m_iBuyColNum	= s.m_pDBEssence->num_buy_item;
	m_iBoothNameLength	= s.m_pDBEssence->max_name_length;
	m_iPrice = s.m_pDBEssence->price;
}
CECIvtrCertificate::~CECIvtrCertificate()
{
}

//	Set item detail information
bool CECIvtrCertificate::SetItemInfo(BYTE* pInfoData, int iDataLen)
{
	CECIvtrItem::SetItemInfo(pInfoData, iDataLen);
	return true;
}

//	Get item icon file name
const char* CECIvtrCertificate::GetIconFile()
{
	return m_pDBEssence->file_icon;
}
//	Get item name
const wchar_t* CECIvtrCertificate::GetName()
{
	return m_pDBEssence->name;
}
//	Get drop model for shown
const char * CECIvtrCertificate::GetDropModel()
{
	return m_pDBEssence->file_matter;
}
//  Get booth model id
const char * CECIvtrCertificate::GetBoothModelID()
{
	return m_pDBEssence->show_model;
}

const char* CECIvtrCertificate::GetBoothBarFile()
{
	char* imageFile = m_pDBEssence->name_image;
	if (*imageFile){
		imageFile += 9;
	}else{
		imageFile = "";
	}
	return imageFile;
}

//	Get item description text
const wchar_t* CECIvtrCertificate::GetNormalDesc(bool bRepair)
{
	if (m_bNeedUpdate)
		return NULL;

	m_strDesc = _AL("");
	//	Try to build item description
	CECStringTab* pDescTab = g_pGame->GetItemDesc();
 	int white = ITEMDESC_COL_WHITE;
 	int namecol = DecideNameCol();

 	//  Item name
 	AddDescText(namecol, true, pDescTab->GetWideString(ITEMDESC_NAME), m_pDBEssence->name);

	AddIDDescText();

	AddExpireTimeDesc();
	
	//  Sell column number
	AddDescText(white, true, pDescTab->GetWideString(ITEMDESC_SELL_COL_NUM), m_iSellColNum);

	//  Buy column number
	AddDescText(white, true, pDescTab->GetWideString(ITEMDESC_BUY_COL_NUM), m_iBuyColNum);

	//  Max booth name length
	AddDescText(white, true, pDescTab->GetWideString(ITEMDESC_MAX_BOOTH_NAME), m_iBoothNameLength);

	//	Price
	AddPriceDesc(white, bRepair);

	//  Extend desc
	AddExtDescText();

	return m_strDesc;
}

///////////////////////////////////////////////////////////////////////////
//	
//	Implement CECIvtrForceToken
//	
///////////////////////////////////////////////////////////////////////////

CECIvtrForceToken::CECIvtrForceToken(int tid, int expire_date) : CECIvtrEquip(tid, expire_date)
{
	m_iCID	= ICID_FORCETOKEN;

	//	Get database data
	elementdataman* pDB = g_pGame->GetElementDataMan();
	DATA_TYPE DataType;
	m_pDBEssence = (FORCE_TOKEN_ESSENCE*)pDB->get_data_ptr(tid, ID_SPACE_ESSENCE, DataType);

	m_iPileLimit	= m_pDBEssence->pile_num_max;
	m_iPrice		= m_pDBEssence->price;
	m_iShopPrice	= m_pDBEssence->shop_price;
	m_iProcType		= m_pDBEssence->proc_type;
	m_i64EquipMask	= EQUIP_MASK64_FORCE_TICKET;

	m_iCurEndurance = 100;
	m_iMaxEndurance = 100;
}

CECIvtrForceToken::CECIvtrForceToken(const CECIvtrForceToken& s) : CECIvtrEquip(s)
{
	m_pDBEssence	= s.m_pDBEssence;
	m_Essence		= s.m_Essence;
}

CECIvtrForceToken::~CECIvtrForceToken()
{
}

//	Set item detail information
bool CECIvtrForceToken::SetItemInfo(BYTE* pInfoData, int iDataLen)
{
	CECIvtrItem::SetItemInfo(pInfoData, iDataLen);

	if (!pInfoData || !iDataLen)
		return true;

	try
	{
		CECDataReader dr(pInfoData, iDataLen);

		m_Essence = *(IVTR_ESSENCE_FORCE_TOKEN*)dr.Read_Data(sizeof (IVTR_ESSENCE_FORCE_TOKEN));
	}
	catch (CECException& e)
	{
		ASSERT(0);
		a_LogOutput(1, "CECIvtrForceToken::SetItemInfo, data read error (%d)", e.GetType());
		return false;
	}

	return true;
}

//	Get item icon file name
const char* CECIvtrForceToken::GetIconFile()
{
	return m_pDBEssence->file_icon;
}

//	Get item name
const wchar_t* CECIvtrForceToken::GetName()
{
	return m_pDBEssence->name;
}

//	Get item description text
const wchar_t* CECIvtrForceToken::GetNormalDesc(bool bRepair)
{
	return m_strDesc;
}

//	Get drop model for shown
const char * CECIvtrForceToken::GetDropModel()
{
	return m_pDBEssence->file_matter;
}


///////////////////////////////////////////////////////////////////////////
//	
//	Implement CECIvtrDynSkillEquip
//	
///////////////////////////////////////////////////////////////////////////

CECIvtrDynSkillEquip::CECIvtrDynSkillEquip(int tid, int expire_date) : CECIvtrEquip(tid, expire_date)
{
	m_iCID	= ICID_DYNSKILLEQUIP;

	//	Get database data
	elementdataman* pDB = g_pGame->GetElementDataMan();
	DATA_TYPE DataType;
	m_pDBEssence = (DYNSKILLEQUIP_ESSENCE*)pDB->get_data_ptr(tid, ID_SPACE_ESSENCE, DataType);

	if (m_pDBEssence)
	{
		for (int i(0); i < ARRAY_SIZE(m_pDBEssence->id_skill); ++ i)
		{
		}
	}

	m_iPileLimit	= m_pDBEssence->pile_num_max;
	m_iPrice		= m_pDBEssence->price;
	m_iShopPrice	= m_pDBEssence->shop_price;
	m_iProcType		= m_pDBEssence->proc_type;
	m_i64EquipMask	= EQUIP_MASK64_DYNSKILLEQUIP1 | EQUIP_MASK64_DYNSKILLEQUIP2;

	m_iCurEndurance = 100;
	m_iMaxEndurance = 100;

	m_bNeedUpdate	= false;
}

CECIvtrDynSkillEquip::CECIvtrDynSkillEquip(const CECIvtrDynSkillEquip& s) : CECIvtrEquip(s)
{
}

CECIvtrDynSkillEquip::~CECIvtrDynSkillEquip()
{
	ClearSkills();
}

void CECIvtrDynSkillEquip::ClearSkills()
{
}

//	Get item name
const wchar_t* CECIvtrDynSkillEquip::GetName()
{
	return m_pDBEssence->name;
}

//	Get item icon file name
const char* CECIvtrDynSkillEquip::GetIconFile()
{
	return m_pDBEssence->file_icon;
}

//	Get drop model for shown
const char * CECIvtrDynSkillEquip::GetDropModel()
{
	return m_pDBEssence->file_matter;
}

bool CECIvtrDynSkillEquip::SetItemInfo(BYTE* pInfoData, int iDataLen)
{
	CECIvtrItem::SetItemInfo(pInfoData, iDataLen);
	return true;
}

//	Get item description text
const wchar_t* CECIvtrDynSkillEquip::GetNormalDesc(bool bRepair)
{
	if (m_bNeedUpdate)
		return NULL;

	m_strDesc = _AL("");

	//	Try to build item description
	CECStringTab* pDescTab = g_pGame->GetItemDesc();	

	int white = ITEMDESC_COL_WHITE;

	int namecol = DecideNameCol();
	if (m_iCount > 1)
		AddDescText(namecol, true, pDescTab->GetWideString(ITEMDESC_NAMENUMBER), GetName(), m_iCount);
	else
		AddDescText(namecol, true, pDescTab->GetWideString(ITEMDESC_NAME), GetName());

	AddIDDescText();

	AddBindDescText();

	AddExpireTimeDesc();

	//	Price
	AddPriceDesc(white, bRepair);

	//	Suite description
	AddSuiteDesc();

	//	Extend description
	AddExtDescText();

	return m_strDesc;
}
///////////////////////////////////////////////////////////////////////////
//	
//	Implement CECIvtrGeneralCard
//	
///////////////////////////////////////////////////////////////////////////

CECIvtrGeneralCard::CECIvtrGeneralCard(int tid, int expire_date) : CECIvtrEquip(tid, expire_date)
{
	m_iCID	= ICID_GENERALCARD;

	memset(&m_Essence, 0, sizeof (m_Essence));
	//	Get database data
	elementdataman* pDB = g_pGame->GetElementDataMan();
	DATA_TYPE DataType;
	m_pDBEssence = (POKER_ESSENCE*)pDB->get_data_ptr(tid, ID_SPACE_ESSENCE, DataType);
	m_pDBSubEssence = (POKER_SUB_TYPE*)pDB->get_data_ptr(m_pDBEssence->id_sub_type, ID_SPACE_ESSENCE, DataType);

	m_iPileLimit	= m_pDBEssence->pile_num_max;
	m_iPrice		= m_pDBEssence->price;
	m_iShopPrice	= m_pDBEssence->shop_price;
	m_iProcType		= m_pDBEssence->proc_type;
	m_i64EquipMask	= m_pDBSubEssence->equip_mask;
	m_iLevelReq		= m_pDBEssence->require_level;

	m_iCurEndurance = 100;
	m_iMaxEndurance = 100;

	m_bNeedUpdate	= true;
}

CECIvtrGeneralCard::CECIvtrGeneralCard(const CECIvtrGeneralCard& s) : CECIvtrEquip(s)
{
	m_Essence		= s.m_Essence;
	m_pDBEssence	= s.m_pDBEssence;
	m_pDBSubEssence = s.m_pDBSubEssence;
}

CECIvtrGeneralCard::~CECIvtrGeneralCard()
{
}

//	Get item name
const wchar_t* CECIvtrGeneralCard::GetName()
{
	return m_pDBEssence->name;
}

//	Get item icon file name
const char* CECIvtrGeneralCard::GetIconFile()
{
	return m_pDBEssence->file_icon;
}

//	Get drop model for shown
const char * CECIvtrGeneralCard::GetDropModel()
{
	return m_pDBEssence->file_matter;
}

bool CECIvtrGeneralCard::SetItemInfo(BYTE* pInfoData, int iDataLen)
{
	CECIvtrItem::SetItemInfo(pInfoData, iDataLen);
	
	if (!pInfoData || !iDataLen)
		return true;
	
	try
	{
		CECDataReader dr(pInfoData, iDataLen);
		
		m_Essence = *(IVTR_ESSENCE_GENERALCARD*)dr.Read_Data(sizeof (IVTR_ESSENCE_GENERALCARD));
		// 加入附加属性说明
		{
			//	Get database data
			elementdataman* pDataMan = g_pGame->GetElementDataMan();
			CECGame::ItemExtPropTable& PropTab = g_pGame->GetItemExtPropTable();
			
			int addon_count = sizeof(m_pDBEssence->addon) / sizeof(m_pDBEssence->addon[0]);
			int i, iSize = 0;
			for(i = 0;i < addon_count;i++) {
				if(m_pDBEssence->addon[i] != 0)
					iSize ++;
			}
			
			if(iSize > 0 && m_aProps.GetSize() == 0) {
				m_aProps.SetSize(iSize, 5);
				for(i = 0; i < addon_count; i++) {
					if(m_pDBEssence->addon[i] != 0) {
						PROPERTY& Prop = m_aProps[i];
						Prop.iType = m_pDBEssence->addon[i];
						Prop.bEmbed = false;
						Prop.bSuite = false;
						Prop.bEngraved = false;
						Prop.bLocal = false;
						
						CECGame::ItemExtPropTable::pair_type Pair = PropTab.get(Prop.iType);
						BYTE bType = Pair.second ? *Pair.first : 0xff;
						bool bConvertFloat = false;
						switch(bType){
						case 45:
							bConvertFloat = true;
							break;
						default:
							break;
						}
						
						DATA_TYPE DataType = DT_INVALID;
						const void* pData = pDataMan->get_data_ptr(m_pDBEssence->addon[i], ID_SPACE_ADDON, DataType);
						if (DataType != DT_EQUIPMENT_ADDON)	{
							ASSERT(DataType == DT_EQUIPMENT_ADDON);
							return 0;
						}
						
						const EQUIPMENT_ADDON* pAddon = (const EQUIPMENT_ADDON*)pData;
						Prop.iNumParam = pAddon->num_params;						
						
						for(int j=0; j < Prop.iNumParam; j++)
						{
							if(j==0)
								Prop.aParams[0] = bConvertFloat ? VisualizeFloatPercent(pAddon->param1) : pAddon->param1;
							else if(j==1)
								Prop.aParams[1] = pAddon->param2;
							else if(j==2)
								Prop.aParams[2] = pAddon->param3;
						}
					}
				}
			}
		}
	}
	catch (CECException& e)
	{
		ASSERT(0);
		a_LogOutput(1, "CECIvtrGeneralCard::SetItemInfo, data read error (%d)", e.GetType());
		return false;
	}
	
	return true;
}
int CECIvtrGeneralCard::CalcGeneralCardProp(int prop_base, int prop_grow)
{
	float ratio_suite = GetSuiteRatio();
	float ratio_profession = GetProfessionRatio();
	float ratio_rebirth = GetRebirthRatio();
	return int((prop_base + a_Max(0, m_Essence.level - 1) * prop_grow) * ratio_suite * ratio_profession * ratio_rebirth + .5f);
}
float CECIvtrGeneralCard::GetProfessionRatio()
{
	float ret(1.f);
	return ret;
}
float CECIvtrGeneralCard::GetSuiteRatio()
{
	float ret(1.f);
	return ret;
}
float CECIvtrGeneralCard::GetRebirthRatio()
{
	float ret(1.f);
	switch(m_Essence.rebirth_times) {
	case 1: ret = 1.3f; break;
	case 2: ret = 1.6f; break;
	default: ret = 1.f; break;
	}
	return ret;
}
float CECIvtrGeneralCard::GetRankRatio()
{
	float ret(1.f);
	switch(m_Essence.rank) {
	case 0: ret = 0.f; break;
	case 1: ret = .65f; break;
	case 2: ret = 1.f; break;
	case 3: ret = 1.35f; break;
	case 4: ret = 1.7f; break;
	default: break;
	}
	return ret;
}
void CECIvtrGeneralCard::AddSuiteDesc()
{
}
//	Get item description text
const wchar_t* CECIvtrGeneralCard::GetNormalDesc(bool bRepair)
{
	return m_strDesc;
}
int CECIvtrGeneralCard::GetSwallowExp()
{
	int ret(m_pDBEssence->swallow_exp);
	// 计算转生消耗的经验
	if (m_Essence.rebirth_times > 0) {
		int rebirth_exp(0);
		for (int i = 1; i < m_Essence.max_level; ++i) 
			rebirth_exp += GetLevelUpExp(i);
		ret += rebirth_exp * m_Essence.rebirth_times;
	}
	// 计算当前等级消耗的经验
	for (int i = 1; i < m_Essence.level; ++i)
		ret += GetLevelUpExp(i);
	// 当前经验
	ret += m_Essence.exp;
	return ret;
}
int CECIvtrGeneralCard::GetLevelUpExp(int level)
{
	static const POKER_LEVELEXP_CONFIG* pConfig = NULL;
	int ret(0);
	if (level < 1 || level >= m_Essence.max_level 
		|| m_Essence.rank < 0 || m_Essence.rank > ELEMENTDATA_NUM_POKER_RANK)
		return 0;
	if (NULL == pConfig) {
		elementdataman *pDataMan = g_pGame->GetElementDataMan();
		DATA_TYPE DataType;
		unsigned int tid = pDataMan->get_first_data_id(ID_SPACE_CONFIG,DataType);
		while(tid) {
			if(DataType == DT_POKER_LEVELEXP_CONFIG) {
				pConfig = (POKER_LEVELEXP_CONFIG*)pDataMan->get_data_ptr(tid,ID_SPACE_CONFIG, DataType);
				break;
			}
			tid = pDataMan->get_next_data_id(ID_SPACE_CONFIG, DataType);
		}
	}
	if (pConfig && level < m_Essence.max_level) 
		ret = static_cast<int>(pConfig->exp[level - 1] * pConfig->exp_adjust[m_Essence.rank] + .5f);
	return ret;
}